# Generated by Django 3.0.1 on 2022-03-04 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='City name')),
                ('est', models.IntegerField(verbose_name='Est year')),
                ('description', models.TextField(verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('country', models.CharField(max_length=50, verbose_name='Country')),
                ('telnumber', models.IntegerField(verbose_name='Telephone number')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityname', models.CharField(max_length=30, verbose_name='City Name')),
                ('place1', models.CharField(max_length=30, verbose_name='Place1')),
                ('place2', models.CharField(max_length=15, verbose_name='Place2')),
                ('place3', models.TextField(max_length=100, verbose_name='Place3')),
            ],
        ),
    ]
