# Generated by Django 3.0.1 on 2022-04-04 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cityapp', '0003_auto_20220315_1023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('info', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Weather',
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Қала', 'verbose_name_plural': 'Қалалар'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Ақпарат', 'verbose_name_plural': 'Ақпарат'},
        ),
        migrations.AlterModelOptions(
            name='famous',
            options={'verbose_name': 'Танымал адамдар', 'verbose_name_plural': 'Танымал адамдар'},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name': 'Демалыс Орын', 'verbose_name_plural': 'Демалыс Орындар'},
        ),
    ]
