# Generated by Django 3.0.1 on 2022-04-13 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cityapp', '0004_auto_20220404_0814'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('surname', models.CharField(max_length=30, verbose_name='Surname')),
                ('country', models.CharField(max_length=30, verbose_name='Country')),
                ('desired_city', models.CharField(max_length=100, verbose_name='Des City')),
                ('desired_place', models.CharField(max_length=100, verbose_name='Des Place')),
                ('date', models.DateField(verbose_name='Date')),
                ('card_num', models.IntegerField(verbose_name='Card number')),
            ],
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
    ]
