# Generated by Django 3.0.1 on 2022-04-22 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cityapp', '0005_auto_20220413_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='email',
            field=models.CharField(default=1, max_length=31),
            preserve_default=False,
        ),
    ]
